import { chromium } from 'playwright';
const url=process.env.PWA_URL || 'http://127.0.0.1:4174/index.html';
const password=process.env.AUTH_TEST_PASSWORD;
if(!password) throw new Error('AUTH_TEST_PASSWORD missing');
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});
const page=await context.newPage();
await page.goto(url,{waitUntil:'domcontentloaded'});
await page.locator('#authScreen:not([hidden])').waitFor();
const initialOptions=await page.locator('#skuSelect option').count();
if(initialOptions!==0) throw new Error(`Locked page exposed options: ${initialOptions}`);
const initialText=await page.locator('body').innerText();
if(initialText.includes('声光漏水报警器')) throw new Error('Locked UI leaked SKU name');
await page.fill('#authPassword','wrong-password');
await page.click('#loginBtn');
await page.waitForTimeout(400);
const wrongError=await page.locator('#authError').innerText();
if(!wrongError.includes('密码错误')) throw new Error(`Wrong password was not rejected: ${wrongError}`);
await page.fill('#authPassword',password);
await page.click('#loginBtn');
await page.locator('#appRoot:not([hidden])').waitFor();
const optionCount=await page.locator('#skuSelect option').count();
if(optionCount!==31) throw new Error(`Expected 31 options after login, got ${optionCount}`);
const firstTitle=await page.locator('#detail h2').innerText();
if(!firstTitle.includes('声光漏水报警器')) throw new Error(`Unexpected first SKU ${firstTitle}`);
await page.selectOption('#skuSelect','2');
const secondTitle=await page.locator('#detail h2').innerText();
if(!secondTitle.includes('3.6×150mm 100条黑色')) throw new Error(`Dropdown switch failed ${secondTitle}`);
await page.getByRole('button',{name:'按单件利润'}).click();
const topProfit=await page.locator('#skuSelect option').first().innerText();
if(!topProfit.includes('手动抽芯铆钉枪')) throw new Error(`Profit sort failed ${topProfit}`);
await page.screenshot({path:'auth-app-mobile.png',fullPage:true});
await page.click('#lockBtn');
await page.locator('#authScreen:not([hidden])').waitFor();
const lockedOptions=await page.locator('#skuSelect option').count();
if(lockedOptions!==0) throw new Error('Lock did not clear options');
await page.screenshot({path:'auth-login-mobile.png',fullPage:true});
await page.fill('#authPassword',password);await page.click('#loginBtn');await page.locator('#appRoot:not([hidden])').waitFor();
await page.evaluate(()=>navigator.serviceWorker.ready);
await context.setOffline(true);
await page.reload({waitUntil:'domcontentloaded'});
await page.locator('#authScreen:not([hidden])').waitFor();
await page.fill('#authPassword',password);await page.click('#loginBtn');await page.locator('#appRoot:not([hidden])').waitFor();
const offlineOptions=await page.locator('#skuSelect option').count();
if(offlineOptions!==31) throw new Error(`Offline unlock failed ${offlineOptions}`);
await context.setOffline(false);
console.log(JSON.stringify({initialOptions,wrongError,optionCount,firstTitle,secondTitle,topProfit,lockedOptions,offlineOptions},null,2));
await browser.close();
