import { chromium } from 'playwright';
const url=process.env.PWA_URL || 'http://127.0.0.1:4175/index.html';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});
const page=await context.newPage();
await page.goto(url,{waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>window.PWA_DATA_VERSION && window.PWA_DATA_VERSION.records>0);
const first=await page.evaluate(()=>({version:window.PWA_DATA_VERSION,loginDisabled:document.getElementById('loginBtn')?.disabled,body:document.body.innerText}));
if(first.loginDisabled) throw new Error('Login remained disabled after external data load');
if(first.body.includes('手动抽芯铆钉枪')||first.body.includes('声光漏水报警器')) throw new Error('Locked UI leaked SKU text');
const networkVersion=await (await page.request.get(new URL('./pwa-data-version.json',url).toString())).json();
const encrypted=await (await page.request.get(new URL('./sku-data.enc.json',url).toString())).json();
if(encrypted.kind!=='SKU-PWA-HYBRID-ENVELOPE') throw new Error('External data is not hybrid envelope');
if(encrypted.records!==networkVersion.records||networkVersion.records!==first.version.records) throw new Error('External record count mismatch');
await page.evaluate(()=>navigator.serviceWorker.ready);
await page.reload({waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>window.PWA_DATA_VERSION && document.getElementById('automationCenter'));
const onlineCenter=await page.locator('#automationCenter').innerText();
if(!onlineCenter.includes('SKU自动化中心')||!onlineCenter.includes('25项自动化路线图')) throw new Error('Automation center missing after SW control');
await context.setOffline(true);
await page.reload({waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>window.PWA_DATA_VERSION && window.PWA_DATA_VERSION.records>0);
const offline=await page.evaluate(()=>({records:window.PWA_DATA_VERSION.records,loginDisabled:document.getElementById('loginBtn')?.disabled,center:document.getElementById('automationCenter')?.innerText||''}));
if(offline.records!==first.version.records) throw new Error(`Offline record mismatch ${offline.records}/${first.version.records}`);
if(offline.loginDisabled) throw new Error('Offline cached external data did not enable login');
if(!offline.center.includes('SKU自动化中心')) throw new Error('Automation center missing offline');
await context.setOffline(false);
console.log(JSON.stringify({records:first.version.records,version:first.version.version,onlineCenter:onlineCenter.slice(0,180),offlineRecords:offline.records},null,2));
await browser.close();
